### ISSUE TITLE
Default root password

### ISSUE THREAD

**Issue by jstr045329** [inversepath/usbarmory#41]
I run this:

usbarmory@usbarmory:/$ sudo apt-get update && apt-get upgrade

and I get the following error:

Err http://ftp.debian.org jessie InRelease                           
  
Err http://ftp.debian.org jessie-updates InRelease                   
  
Err http://ftp.debian.org jessie Release.gpg
  Could not resolve 'ftp.debian.org'

**< more stuff like this>**

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://ftp.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'ftp.debian.org'

W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'ftp.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
**E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?**

Do I need to enter the su password to solve this? If so, what is the default password or how do I set it up?

**Comment by abarisani** [comment]
There is no default root password (otherwise you wouldn't see the first command running).

But you also need sudo before the `apt-get upgrade` command, this is why you are seeing the error.

Also it looks like you are not sharing your Internet connection with the USB armory, to do so please follow instructions at https://github.com/inversepath/usbarmory/wiki/Host-communication

If you have troubles please contact our support email directly.

Cheers
